//partners section
export const partners = [
      { id: 1,
        partImage: "assets/img/verve.png",
        partUrl: "#",
        delay: "0",
        alt: "LindaPay",
       },
       { id: 2,
        partImage: "assets/img/mastercard.png",
        partUrl: "#",
        delay: "200",
        alt: "LindaPay",
       },
       { id: 3,
        partImage: "assets/img/flutterwave.png",
        partUrl: "#",
        delay: "400",
        alt: "LindaPay",
       },
       { id: 4,
        partImage: "assets/img/gtbank.png",
        partUrl: "#",
        delay: "600",
        alt: "LindaPay",
       },
       
 ];