//testimonial section
export const productconten = [
    { id: 0,
     title: "What Users Have to Say",
    },
    { id: 1,
        testimonialImage: "assets/img/avatar-01.jpg",
        desc: "“It's a cool escrow platform for receiving payments from my clients. The favourite part for me is its easy to use and gives me the peace of mind I need to focus on service delivery without chasing payment.”",
        testimonialName: "Nkem Jude",
        identity: " - Freelance Graphics Designer",
       },
       { id: 2,
        testimonialImage: "assets/img/avatar-02.jpg",
        desc: "“The first time  I used it to order a generating set for my business, I was skeptical, to be honest. My consolation was that I could still see my money on my dashboard till the merchant delivered my order. Then I fully understood its value.”",
        testimonialName: "Glory Edet",
        identity: " - Fashion Designer",
       },
       { id: 3,
        testimonialImage: "aassets/img/avatar-03.jpg",
        desc: "“Thanks to LindaPay we didn't go ahead to deliver an order without seeing the payment on our dashboard. Before now, we would have incurred logistics cost and made no sales. You have redefined pay on delivery for us.”",
        testimonialName: "Mark Magnus",
        identity: " - Merchant",
       },
       
 ];